name = "happy-hour"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "happy-hour"
database_id = "placeholder-create-with-wrangler"
